### ISSUE TITLE
False positive: anonymous classes derived from Exception is not named *Exception

### ISSUE THREAD

**Issue by RichardBradley** [sksamuel/scalac-scapegoat-plugin#106]
I have some anonymous classes which inherit from exception, like:

```
throw new ErrorCodeException("it went wrong") {
  override def errorCode = 123
  override def jsonEntity = ...
}
```

This triggers "Class derived from Exception is not named *Exception" with detail
```
final class $anon extends myapp.ErrorCodeException ....
```

(Whether this is pretty code is a separate question, but I don't think it should count as breaking this rule. :-) )

**Comment by sksamuel** [comment]
You're right, this shouldn't trigger a warning.
