### ISSUE TITLE
Request for advice: false positives on "Looks Like Interpolated String" from class names

### ISSUE THREAD

**Issue by RichardBradley** [sksamuel/scalac-scapegoat-plugin#112]
We have some logging macros which add the current class name and line number to logging statements.

In many cases, the class name will contain a "$" (e.g. objects, inner classes).

These result in a great many false positive warnings for "Looks Like Interpolated String"

Code like:
```
    } recoverWith {
      case e: Throwable =>
        log.error(e, s"Searching for xyz with uid $uid failed.")
        ...
    }
```

gives this warning, because it gets translated by our logging macros into (something like):

```
    } recoverWith {
      case e: Throwable =>
        log.error(e,
          "myapp.MyClass$anonfun" + ":" + "123" + " " +
          s"Searching for xyz with uid ${uid} failed.")
        ...
    }
```

Can you think of any way to avoid this?

Perhaps "Looks Like Interpolated String" could check that there is a variable in scope with the name "anonfun"?

Thanks,

Rich

**Comment by sksamuel** [comment]
I should be able to fix it by filtering out $anonfun really.

**Comment by RichardBradley** [comment]
Thanks
