### ISSUE TITLE
False positive / possible scalac issue? Case object with same name as abstract class.

### ISSUE THREAD

**Issue by RichardBradley** [sksamuel/scalac-scapegoat-plugin#118]
Akka has some case objects with the same name as an adjacent abstract class (which they extend). This is rather odd, but I think it's for Java compat. (e.g. ["ActorPublisherMessage.Cancel"](https://github.com/akka/akka/blob/a9d6e439294aee60af7c36cc51ccfc9ba32dc6be/akka-stream/src/main/scala/akka/stream/actor/ActorPublisher.scala#L54))

This confuses the "SuspiciousMatchOnClassObject" inspection, but it also seems to produce an incorrect "match may not be exhaustive" warning from scalac.

Can you work out what's going on here?

Here's a failing test for scapegoat:

```
scala/com/sksamuel/scapegoat/inspections/matching/SuspiciousMatchOnClassObjectTest.scala
index c72e3b8..da88e7b 100644
--- a/src/test/scala/com/sksamuel/scapegoat/inspections/matching/SuspiciousMatchOnClassObjectTest.scala
+++ b/src/test/scala/com/sksamuel/scapegoat/inspections/matching/SuspiciousMatchOnClassObjectTest.scala
@@ -152,6 +152,32 @@ class SuspiciousMatchOnClassObjectTest
         compileCodeSnippet(code)
         compiler.scapegoat.feedback.warnings.size shouldBe 0
       }
+
+      "for case objects with adjacent classes of the same name" in {
+        val code = """sealed abstract class ActorPublisherMessage
+                     |
+                     |object ActorPublisherMessage {
+                     |  final case object Cancel extends Cancel
+                     |  sealed class Cancel extends ActorPublisherMessage
+                     |
+                     |  final case object SubscriptionTimeoutExceeded extends SubscriptionTimeoutExceeded
+                     |  sealed abstract class SubscriptionTimeoutExceeded extends ActorPublisherMessage
+                     |}
+                     |
+                     |object A {
+                     |  def handle(a: ActorPublisherMessage) = {
+                     |    a match {
+                     |      case ActorPublisherMessage.Cancel =>
+                     |        println("x")
+                     |      case ActorPublisherMessage.SubscriptionTimeoutExceeded =>
+                     |        println("y")
+                     |    }
+                     |  }
+                     |}""".stripMargin
+        compileCodeSnippet(code)
+        compiler.scapegoat.feedback.warnings.size shouldBe 0
+      }
+
       "for instances of case class" in {

```

The match above is given a warning by scalac:
```
warning: match may not be exhaustive.
It would fail on the following input: Cancel()
    a match {
    ^
```

... but this warning (and scapegoat's warning) is incorrect, as the match will actually catch "Cancel" objects and isn't matching on the class name (also "Cancel").

If you run the following in `scala`, you'll see that the "case Cancel" is being interpreted as a literal "==" match on the case object, and not for the type "Cancel", so the warning from `scalac` is incorrect:

```
scala> sealed abstract class ActorPublisherMessage
defined class ActorPublisherMessage

scala> object ActorPublisherMessage {
     |   final case object Cancel extends Cancel
     |   sealed class Cancel extends ActorPublisherMessage
     |
     |   final case object SubscriptionTimeoutExceeded extends SubscriptionTimeoutExceeded
     |   sealed abstract class SubscriptionTimeoutExceeded extends ActorPublisherMessage
     | }
defined object ActorPublisherMessage
warning: previously defined class ActorPublisherMessage is not a companion to object ActorPublisherMessage.
Companions must be defined together; you may wish to use :paste mode for this.

scala>

scala> object A {
     |   def handle(a: ActorPublisherMessage) = {
     |     a match {
     |       case ActorPublisherMessage.Cancel =>
     |         println("x")
     |       case ActorPublisherMessage.SubscriptionTimeoutExceeded =>
     |         println("y")
     |     }
     |   }
     | }
<console>:11: warning: match may not be exhaustive.
It would fail on the following input: Cancel()
           a match {
           ^
defined object A

scala> val msg: ActorPublisherMessage = ActorPublisherMessage.Cancel
msg: ActorPublisherMessage = Cancel

scala> A.handle(msg)
x
```

1. Do you agree that the warning from scalac is incorrect? Or have I misunderstood it?
2. Do you think that this is a legal pattern match? I can't decide what the [language spec](http://www.scala-lang.org/files/archive/spec/2.11/08-pattern-matching.html) declares here. Does "case Cancel" refer to the type or the case object according to the spec?
3. Do you think that scalac is changing whether "case Cancel" refers to the type or the case object from one compile phase to the next, and that might be why the warning is issued by scalac and scapegoat but the match does then work correctly?
4. WTH is going on here? Should I send this to the scala mailing list? To the Akka mailing list?

Thanks,

Rich

**Comment by gshakhn** [comment]
The scalac warning is indicating that instances of the class Cancel won't be caught by the pattern match.

````
scala> val c = new ActorPublisherMessage.Cancel()
c: ActorPublisherMessage.Cancel = ActorPublisherMessage$Cancel@206564e9

scala> A.handle(c)
scala.MatchError: ActorPublisherMessage$Cancel@206564e9 (of class ActorPublisherMessage$Cancel)
  at A$.handle(<console>:13)
````

**Comment by RichardBradley** [comment]
Oh. It seems obvious when you put it like that :-)

So [this Akka code](https://github.com/akka/akka/blob/a9d6e439294aee60af7c36cc51ccfc9ba32dc6be/akka-stream/src/main/scala/akka/stream/actor/ActorPublisher.scala#L54) is just broken, right?

All the ActorPublishers which have code like 
```
  override def receive = {
    case ActorPublisherMessage.Cancel =>
      ... do stuff
  }
```

(e.g. [TokenSourceActor](https://github.com/akka/akka/blob/a9d6e439294aee60af7c36cc51ccfc9ba32dc6be/akka-http-core/src/main/scala/akka/http/impl/engine/TokenSourceActor.scala#L22))

will fail if you send them a "new ActorPublisherMessage.Cancel()"

I'll email the Akka list and see if they can straighten this out.


This still means that the `scapegoat` warning is bugged, though, doesn't it?
The "match" here is definitely matching on the case object, so it's not a "Suspicious match on class object".

**Comment by RichardBradley** [comment]
Oh, hang on.

This isn't some mysterious problem; it's just that the "sealed class Cancel extends ActorPublisherMessage" is missing an "abstract" modifier.

That makes the "match" total above.

I'll raise an Akka PR.

I'll clarify if this is a real scapegoat issue (I think it is). Maybe a new issue is called for to sweep away this distraction :-)

**Comment by RichardBradley** [comment]
Hmm -- fixing the missing "abstract" also fixes the scapegoat warning, so I think this is a non issue.

Thanks

**Comment by RichardBradley** [comment]
(For clarification: the test at the top of this thread does fail, and I think wrongly. However that's a rather pathological case, so it's not worth looking into. The main fix here will be to update my Akka version, which should fix this warning on my project.)
