### ISSUE TITLE
False Positive (?): Empty if Statement

### ISSUE THREAD

**Issue by xanderdunn** [sksamuel/scalac-scapegoat-plugin#125]
This is a common asynchronous observable pattern in [RxScala](): 
```scala
Observable(
  subscriber => {
    new Thread(new Runnable() {
      def run() : Unit = {
        if (subscriber.isUnsubscribed) {()}
        subscriber.onNext(Some(0))
        if (!subscriber.isUnsubscribed) { // after sending all values we complete the sequence
          subscriber.onCompleted()
        }
      }
    }).start()
  }
)
```

and scapegoat gives the warning: 
```bash
[warning] FILE:19: Empty if statement
          if (subscriber.isUnsubscribed)
  ()
else
  ()
```

Should this be considered an "empty" if statement?  It has a return value in it: `Unit` (written here as `()`).

**Comment by jawshooah** [comment]
Correct me if I'm wrong, but isn't that just a no-op? What's the point of having it there? For example:

```scala
def foo() {
  if (true) {()}
  println("Still printed")
}

foo()  // "Still printed"
```

**Comment by xanderdunn** [comment]
@jawshooah You're completely right!  The typical RxScala pattern has a `return` there rather than `()`.  I thought I was being clever by using `()` instead of `return`, but this has the desired effect only when the function's return type is `Unit` and the `()` is on the last line of the function's body.  Clearly, I'm new to Scala and scapegoat had precisely the right effect here!  Thanks!
