### ISSUE TITLE
False Positive: length == 0 in a non-Traversable class

### ISSUE THREAD

**Issue by leifwickland** [sksamuel/scalac-scapegoat-plugin#94]
In the following
```scala
case class Duration(start: Long, stop: Long) {
  def length: Long = end - stop
  def isEmpty: Boolean = length == 0
```

The final line is flagged with

`Avoid Traversable.size == 0`

by

`com.sksamuel.scapegoat.inspections.collections.AvoidSizeEqualsZero`

Clearly the Duration class isn't an instance of Travereable, so the warning is inappropriate.

**Comment by sksamuel** [comment]
Thanks for bug report. Fixed.
